FROM centos:6.7

ENV SEI_HOST_URL localhost
ENV SEI_ORGAO MP

COPY files/install-pen.sh /install-pen.sh
COPY files/msttcore-fonts-2.0-3.noarch.rpm /usr/local/bin/

RUN bash /install-pen.sh

COPY certs/cacert.pem	/etc/ssl/certs/

# Ajustando a hora do container para TimeZone BRT
COPY files/Sao_Paulo /etc/localtime

# Copia dos fontes e customização dos Configuracao[SEI|Sip].php
COPY fontes/ /opt/  
COPY files/ConfiguracaoSEI.php /opt/sei/config/ConfiguracaoSEI.php
COPY files/ConfiguracaoSip.php /opt/sip/config/ConfiguracaoSip.php

COPY files/sei.ini /etc/php.d/sei.ini
COPY files/sei.conf /etc/httpd/conf.d/

# Instalação do Modulo Barramento
COPY mod-sei-barramento/ /opt/sei/web/modulos/mod-sei-barramento
RUN mv /opt/sei/web/modulos/mod-sei-barramento/sei_atualizar_versao_modulo_pen.php /opt/sei/scripts/sei_atualizar_versao_modulo_pen.php && \
    mv /opt/sei/web/modulos/mod-sei-barramento/sip_atualizar_versao_modulo_pen.php /opt/sip/scripts/sip_atualizar_versao_modulo_pen.php && \
    mv /opt/sei/web/modulos/mod-sei-barramento/verificar-servicos.sh /opt/sei/bin/ 

# Correção da permissao e dono do arquivo para geracao de PDF
RUN chown -R 0:48 /opt/ && \
    chmod -R 750 /opt && \
    chmod -R 570 /opt/sei/temp && \
    chmod -R 570 /opt/sip/temp
    
# Cria o diretório de log's    
RUN mkdir -p /var/log/supervisor/

# Cria um arquivo default de referência
RUN echo_supervisord_conf > /etc/supervisord.conf

COPY files/supervisord.conf /conectagov.conf
RUN cat /conectagov.conf >> /etc/supervisord.conf

COPY entrypoint-pen.sh /entrypoint-pen.sh
ENTRYPOINT ["/entrypoint-pen.sh"]

EXPOSE 80
EXPOSE 443

#[RANCHER] contorno de problema no rancher e memcached
COPY files/InfraCache.php /opt/infra/infra_php/InfraCache.php
ENV CACHE_TIMEOUT 1

COPY files/httpd-foreground /usr/local/bin/
CMD ["/usr/bin/supervisord","-n"]
